### ISSUE TITLE
DateTime.UtcNow != DateTime.Now

### ISSUE THREAD

**Issue by BrettBurbidge** [Prasadnair/RateLimitDemo#1]
Great solution!  Love the work. Small bug here. 

You are comparing UTC-time to non-UTC time. 

The requests will take (depending on where you live) 6+ hours to resolve, not 2 seconds. 

I just changed this if statement to DateTime.UtcNow for the fix. 
`  if (_clientStatistics!=null
            && *****DateTime.Now***** <_clientStatistics.LastSuccessfulResponseTime.AddSeconds(rateLimitDecorator.TimeWindow)
            && _clientStatistics.NumberofRequestsCompletedSuccessfully ==rateLimitDecorator.MaxRequests)
        {`

` _clientStats.LastSuccessfulResponseTime = *****DateTime.UtcNow*****;`

https://github.com/Prasadnair/RateLimitDemo/blob/fd66a65ce332b902a9ce1b1131821084d419826d/RateLimitingDemo/CustomMiddleware/Middlewares/RateLimitingMiddleware.cs#L37

**Comment by Prasadnair** [comment]
much appreciated. I didn't notice.
